# Stage 1: Build the Ionic App
FROM node:20-alpine AS build
WORKDIR /app

# Install Ionic CLI globally (required for ionic build)
RUN npm install -g @ionic/cli

# Install dependencies
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Copy source and build
COPY . .
# This replaces your "npx ionic build" command
RUN ionic build --prod

# Stage 2: Serve with Nginx
FROM nginx:alpine

# Remove default Nginx config
RUN rm /etc/nginx/conf.d/default.conf
# Copy your custom config (see step 2 below)
COPY nginx.conf /etc/nginx/conf.d/default.conf

# IMPORTANT: Copy the 'www' folder generated by Ionic
COPY --from=build /app/www /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]