server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Redirects all traffic to index.html for Ionic/Angular routing
        try_files $uri $uri/ /index.html;
    }
}